### PR TITLE
docs: improve "Quick Start" documentation in top-level and sir example READMEs

### LINKED ISSUE #564: Improve "Quick Start" documentation in top-level README and `sir` example README
We should improve the documentation in the "Quick Start" sections in the top-level README and in the `sir` example README to address some things that came up in discussion #559 and also that were changed due to the fixes in #335.

### PR DESCRIPTION
**Pull request by LSarribouette**
Fixes #564

Improves the documentation related to discussion #559.

Edited by Chris to retroactively reference a new issue describing the changes.

### CODE REVIEW

**Comment by LSarribouette** [comment]
Hi! It is my first fork and pull request on someone else's repo. Please let me know if I should do anything differently :)

**Comment by chrispcampbell** [comment]
Hi @LSarribouette, thanks for taking the time to contribute these edits!

Your discussion thread prompted me to finally address #335 today (which I will merge and release tomorrow).  That will render your proposed text somewhat inaccurate, so I will need to change it a bit before merge, and I will work on that tomorrow.  I will probably move part of the text to a "troubleshooting" section in the wiki.

In any case, I appreciate your edits because they make it more obvious where I can improve the docs.

> It is my first fork and pull request on someone else's repo. Please let me know if I should do anything differently :)

You did it correctly, and you even included a well-formatted pull request title, so all good from my perspective :)

**Comment by LSarribouette** [comment]
Awesome, thanks for your work!

**Comment by chrispcampbell** [comment]
I updated your PR per my previous comments, so the text is different than the proposed but the areas touched are the same, and we now point to the wiki page with a new "Troubleshooting" section (that page will be good to flesh out as time goes on).  Thanks again for pointing me in the right direction!

**Review by chrispcampbell — APPROVED** [review]

**Pull request merged**
