### PR TITLE
feat: add support for additional trig functions

### LINKED ISSUE #382: Add trig all six basic trig function support
Currently SDE only supports two trigonometry functions: SIN() and COS().  Supporting all of the six core trig functions should be implemented.

SIN
COS
TAN
ARCSIN
ARCCOS
ARCTAN

Needed for a model I'm working on.

### PR DESCRIPTION
**Pull request by travisfranck**
Fixes #382

Added TAN, ARCSIN, ARCCOS, and ARCTAN function support to SDE.  Included tests.

### CODE REVIEW

**Review by chrispcampbell — APPROVED** [review]
Looks great, thanks!

I added the 4 new functions to the [Supported Vensim Functions](https://github.com/climateinteractive/SDEverywhere/wiki/Supported-Vensim-Functions) page on the wiki.

I'll also make sure the new functions are covered in the new unit tests that are currently out for review in another PR.

**Comment by chrispcampbell** [comment]
I think the GH Actions are not running correctly for PRs submitted from a fork.  I'll look into that and make sure builds are working before I merge this.

**Comment by travisfranck** [comment]
I'm going to move back to working in the main repo now unless it is useful for me to test using forks for collaboration.

**Comment by chrispcampbell** [comment]
I fixed the issue that prevented the build workflow running, and the build was successful, so I'll merge this.

**Pull request merged**
